version: "3.3"

services:
  mysqlspring:
      container_name: mysqlspring
      image: mysql:5.7
      restart: unless-stopped
      environment:
        - MYSQL_DATABASE=tpachato
        - MYSQL_ALLOW_EMPTY_PASSWORD= yes
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
      
    
  spring:
      depends_on:
        - mysqlspring
      image: oussemamestiri/spring:jenkins
      restart: on-failure
      ports:
        - "8089:8089"
      environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqlspring:3306/tpachato?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true

  

volumes:
  db:
